name: Update Package Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "9 18 * * 0"

jobs:
  dep_update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true

      - name: Update minor and patch-level dependencies
        run: go get -t -u ./...

      - name: Tidy
        run: go mod tidy

      - name: Create pull request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e
        with:
          title: "Update package dependencies + tidy"
          body: |
            This is an automated pull request to update package dependencies and tidy.
            Please review the changes and merge if they look good.
          branch: dep-update
          commit-message: "Update package dependencies + tidy"
          delete-branch: true
